name: Reusable - Build and Push Docker Image

on:
  workflow_call:
    inputs:
      dockerfile_context:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Dockerfile linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile_context }}/Dockerfile
          failure-threshold: info
          trusted-registries: docker.io

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repository }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.dockerfile_context }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }} # coloca latest tbm?
          labels: ${{ steps.meta.outputs.labels }} # confirmar quais labels estão sendo adicionadas melhor label ou annotation?
          # https://docs.docker.com/build/ci/github-actions/secrets/

      - name: Run Dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: ${{ steps.meta.outputs.tags }}
          format: 'list'
          exit-code: '0'
          exit-level: 'warn'
          ignore: 'CIS-DI-0001,DKL-DI-0006'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Test
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.dockerfile_context }}
          cache-from: type=gha
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: Sign image with a key
#        env:
#          TAGS: ${{ steps.docker_meta.outputs.tags }}
#          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
#          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
#          DIGEST: ${{ steps.build-and-push.outputs.digest }}
#        run: |
#          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
#
# Legal de por no github actions annotations
# cosign sign --key cosign.key \
# -a "repo=${{github.repository}} \
# -a "workflow=${{github.workflow}} \
# -a "ref=${{github.sha}} \
# essas annotations já tem na imagem não?